version: "3"
services:
   nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - var/nginx
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
